version: "3.8"

services:
  postgres:
    container_name: postgres
    build:
      context: ./docker/postgres
    image: postgres_transcendence
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - transcendence_net
    restart: always

  # app:
  #   build:
  #     context: ./docker/django
  #   restart: unless-stopped
  #   command: daphne transcendence.asgi:application -u /usr/src/app/daphne.sock
  #   volumes:
  #     - $PWD:/usr/src/app

  # nginx:
  #   container_name: nginx
  #   build: 
  #     context: ./docker/nginx
  #   image: nginx_transcendence
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - nginx_net
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - $PWD:/usr/src/app
  #   depends_on:
  #     - app

networks:
  transcendence_net:
    name: transcendence_net
    driver: bridge
  
  nginx_net:
    name: nginx_net
    driver: bridge
