version: "3.8"

services:
    postgres:
        container_name: postgres
        build:
            context: ./src/docker/postgres
        image: postgres_transcendence
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - transcendence_net
        restart: always

networks:
    transcendence_net:
        name: transcendence_net
        driver: bridge
