version: "3.8"

services:
    postgres:
        container_name: postgres
        build:
            context: .
        image: postgres_transcendence
        env_file:
            - .env
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        expose:
            - "5432:5432"
        networks:
            - transcendence_net
        restart: always
    django:
        container_name: django
        build: ./src
        image: django_transcendence
        env_file:
            - .env
        ports:
            - "8000:8000"
        networks:
            - transcendence_net
        depends_on:
            - postgres
    nginx:
        container_name: nginx
        build: ./src
        ports:
            - "8080:8080"
        networks:
            - transcendence_net
        restart: always


networks:
    transcendence_net:
        name: transcendence_net
        driver: bridge
