# Generated by Django 5.0.4 on 2024-04-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournamentID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('profilePicture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('totalPoints', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('matchesTotal', models.IntegerField(default=0)),
                ('matchesWon', models.IntegerField(default=0)),
                ('matchesLost', models.IntegerField(default=0)),
                ('matchesDraw', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('pointsUser1', models.IntegerField(default=0)),
                ('pointsUser2', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('tournamentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_match', to='api.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_match', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friendID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='api.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTournament',
            fields=[
                ('userTournamentID', models.AutoField(primary_key=True, serialize=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='api.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user')),
            ],
        ),
    ]
