# Generated by Django 5.0.4 on 2024-04-26 11:55

from django.db import migrations


def generate_users_data(apps, schema_editor):
    User = apps.get_model("api", "User")
    for i in range(10):
        User.objects.create_user(username=f"user{i+1}", password=f"pass123")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_users_data)
    ]
