# Generated by Django 5.0.4 on 2024-05-08 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240426_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
