# Generated by Django 3.2.19 on 2024-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_auto_20240412_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField(default=15)),
                ('height', models.IntegerField(default=15)),
                ('color', models.CharField(default='white', max_length=50)),
                ('vx', models.IntegerField(default=4)),
                ('vy', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='IA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='player',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='vx',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='player',
            name='vy',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='player',
            name='width',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='player',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
