# Generated by Django 5.0.4 on 2024-04-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=10)),
                ('height', models.FloatField(default=10)),
                ('vx', models.FloatField(default=1)),
                ('vy', models.FloatField(default=1)),
                ('color', models.CharField(default='white', max_length=50)),
                ('state', models.CharField(default='stopped', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=10)),
                ('height', models.FloatField(default=10)),
                ('color', models.CharField(default='white', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profilePicture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('matchesTotal', models.IntegerField(default=0)),
                ('matchesWon', models.IntegerField(default=0)),
                ('matchesLost', models.IntegerField(default=0)),
                ('paddle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.paddle')),
            ],
        ),
    ]
