# Generated by Django 3.2.19 on 2024-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_tournamentid_alter_user_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField(default=15)),
                ('height', models.IntegerField(default=15)),
                ('color', models.CharField(default='white', max_length=50)),
                ('vx', models.IntegerField(default=4)),
                ('vy', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(default=15)),
                ('height', models.IntegerField(default=80)),
                ('color', models.CharField(default='white', max_length=50)),
                ('vx', models.IntegerField(default=4)),
                ('vy', models.IntegerField(default=4)),
                ('score', models.IntegerField(default=0)),
                ('IA', models.BooleanField(default=False)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
            ],
        ),
    ]
