# Generated by Django 5.0.4 on 2024-04-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_ball_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournamentId',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='usertournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='usertournament',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserTournament',
        ),
    ]
