# Generated by Django 5.0.4 on 2024-04-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_ball_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=640)),
                ('height', models.IntegerField(default=400)),
                ('color', models.CharField(default='black', max_length=50)),
                ('painting', models.CharField(default='white', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='vx',
            new_name='v',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vy',
        ),
        migrations.AddField(
            model_name='player',
            name='keyDown',
            field=models.CharField(default='ArrowDown', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='keyUp',
            field=models.CharField(default='ArrowUp', max_length=50),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball', to='game.ball')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='game.course')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.player')),
            ],
        ),
    ]
