# Generated by Django 5.0.4 on 2024-04-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_course_rename_vx_player_v_remove_player_vy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='field',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='keyDown',
        ),
        migrations.RemoveField(
            model_name='player',
            name='keyUp',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
