# Generated by Django 5.0.4 on 2024-04-23 12:49

from django.db import migrations


def generate_users_data(apps, schema_editor):
    User = apps.get_model("game", "User")
    for i in range(10):
        User.objects.create(name=f"user{i+1}", password=f"pass123")


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_tournament_user_match_friend_usertournament'),
    ]

    operations = [
        migrations.RunPython(generate_users_data)
    ]
