# Generated by Django 5.0.4 on 2024-04-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
