# Generated by Django 5.0.4 on 2024-04-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_delete_ball_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=10)),
                ('height', models.FloatField(default=10)),
                ('vx', models.FloatField(default=1)),
                ('vy', models.FloatField(default=1)),
                ('color', models.CharField(default='white', max_length=50)),
                ('state', models.CharField(default='stopped', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=10)),
                ('height', models.FloatField(default=10)),
                ('color', models.CharField(default='white', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='matchesDraw',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='pointsUser1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='pointsUser2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalPoints',
        ),
        migrations.AddField(
            model_name='match',
            name='ball',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.ball'),
        ),
        migrations.AddField(
            model_name='user',
            name='paddle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.paddle'),
        ),
    ]
