# Generated by Django 5.0.4 on 2024-04-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_ball_paddle_delete_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friendID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournamentID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='id',
        ),
    ]
