# Generated by Django 5.0.4 on 2024-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_friendid_friend_id_rename_matchid_match_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default='2024-04-15'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
