# Generated by Django 5.0.4 on 2024-04-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
    ]
