# Generated by Django 5.0.4 on 2024-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
