# Generated by Django 5.0.4 on 2024-04-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournamentId',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
    ]
